spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
  h2:
    console:
      enabled: true

handlebars:
  suffix: .html
